### ISSUE TITLE
allow specifying the size of bytes for `return-broken-stream`

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/storage-testbench#162]
I'm trying to reproduce an issue where json parsing is failing due to the response body being effectively empty due to a broken stream. I'd like to be able to specify something like `return-broken-stream-0B` to break the stream at 0B instead of the default 1KiB.

**Comment by frankyn** [comment]
I'm picking this up.

Status: Prototyping with @BenWhitehead: have an ongoing-branch https://github.com/googleapis/storage-testbench/compare/frank-test?expand=1

**Comment by BenWhitehead** [comment]
Features request to enable fixing https://github.com/googleapis/java-storage/issues/1154
