### ISSUE TITLE
Emulator returning incorrect "error" JSON

### ISSUE THREAD

**Issue by devjgm** [googleapis/storage-testbench#170]
From https://cloud.google.com/apis/design/errors#http_mapping, an example error json blob looks like:

```json
{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "translate.googleapis.com"
        }
      }
    ]
  }
}
```
However, due to the code here (maybe only here, or maybe in other places too)
https://github.com/googleapis/storage-testbench/blob/24b78063ec39c8b7c7dc7e5648dff0a18dac2cf3/testbench/error.py#L37

The emulator returns JSON errors that look like

```json
  {
     "code": ...,
     "message": ...
  }
```
Notice that this blob looks like the _contents_ of the "error" object. I think the emulator should probably return the following instead 

```json
  "error": { 
     "code": ...,
     "message": ...
  }
```

Do we know of any users of the emulator who would break with this change?

Related to: https://github.com/googleapis/google-cloud-cpp/issues/7644

**Comment by ddelgrosso1** [comment]
@devjgm has anyone gotten back to you with an answer to this? I know there was some internal chat with regards to this but not sure if a final consensus was communicated.

**Comment by coryan** [comment]
AFAICT, the client libraries would be fine if we fixed this, but it is not needed.  For the C++ client library this is a nice to have, the tests for the library work regardless.

**Comment by ddelgrosso1** [comment]
Based on the comments that this is a nice to have I am changing the priority and moving it to a feature request.

**Comment by devjgm** [comment]
To be clear, I think fixing this is "nice to have" for the C++ client library because it can handle the responses from the emulator in either format. However, I do think that the emulator is returning the wrong thing. It seems more like a bug than a feature request.
