### ISSUE TITLE
update python version

### ISSUE THREAD

**Issue by anukaal** [googleapis/storage-testbench#241]
add support for python versions 3.6, 3.7, 3.8, 3.9, 3.10

**Comment by coryan** [comment]
We already test with 3.6, 3.8, and 3.9.  I think we use it with 3.10 also.  Is there a particular problem that you think would be solved by testing with other versions?

**Comment by NaincyKumariKnoldus** [comment]
Hello @coryan Can I test it for python 3.10?

**Comment by coryan** [comment]
I just created a PR that runs the tests with 3.7 and 3.10, filling up the test matrix.
